name: coupon
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^4.2.0
  firebase_auth: ^3.4.0
  firebase_core: ^2.0.0
  firebase_database: ^10.0.1
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.5+1
  freezed_annotation: 
  hashids2: ^2.0.0
  hooks_riverpod: ^2.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.4
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true
